<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <UseWPF>true</UseWPF>
    <OutputType>WinExe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\PrinterShare.Contracts\PrinterShare.Contracts.csproj" />
    <PackageReference Include="Grpc.AspNetCore" Version="2.64.0" />
    <PackageReference Include="MaterialDesignThemes" Version="5.1.0" />
    <PackageReference Include="Zeroconf" Version="3.6.11" />
    <PackageReference Include="System.Drawing.Common" Version="8.0.7" />
  </ItemGroup>
</Project>
